name: medicare
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.0.0
  cupertino_icons: ^1.0.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.1 
  geolocator: ^9.0.2
  permission_handler: ^11.0.1
  cloud_firestore: ^5.0.0
  carousel_slider: ^4.2.1
  geocoding: ^3.0.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  http: ^1.3.0
  
  
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.json
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
    - assets/banner4.jpg
    - assets/medicine login1.jpg
    - assets/medicines.json
    - assets/tablet.jpg
